server:
  port: 8001

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/helperdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 123456

mybatis-plus:
  mapper-locations:
    - classpath:mappers/*
  #实体类别名配置
  type-aliases-package: com.AkiTeam.mapper
  #日志配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

